# 用于创建分钟级的表
# 1.需要替换数据库 IronDB
# 2.需要替换表名称 i1509_5Min
USE IronDB;
CREATE TABLE `i1509_5Min` (
    `id` int(5) unsigned NOT NULL AUTO_INCREMENT,
    `InstrumentID` varchar(10) DEFAULT NULL,
    `MySQLTimeStamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    `TradingDay` date DEFAULT NULL,
    `UpdateTime` time DEFAULT NULL,
    `MinuteNum` int(3) DEFAULT NULL,
    `LastPrice` float DEFAULT NULL,
    `AskPrice1` float DEFAULT NULL,
    `BidPrice1` float DEFAULT NULL,
    `AskVolume1` int(15) DEFAULT NULL,
    `BidVolume1` int(15) DEFAULT NULL,
    `AveragePrice` float DEFAULT NULL,
    `OpenPrice` float DEFAULT NULL,
    `ClosePrice` float DEFAULT NULL,
    `HighestPrice` float DEFAULT NULL,
    `LowestPrice` float DEFAULT NULL,
    `UpperLimitPrice` float DEFAULT NULL,
    `LowerLimitPrice` float DEFAULT NULL,
    `OpenInterest` int(15) DEFAULT NULL,
    `PreOpenInterest` int(11) DEFAULT NULL,
    `PreClosePrice` float DEFAULT NULL,
    `PreDelta` varchar(20) DEFAULT NULL,
    `PreSettlementPrice` float DEFAULT NULL,
    `Volume` int(20) DEFAULT NULL,
    `StartVolume` int(20) DEFAULT NULL,
    `EndVolume` int(20) DEFAULT NULL,
    `SubDataNum` int(15) DEFAULT '0',
    `BollUp` float DEFAULT NULL,
    `BollDown` float DEFAULT NULL,
    `BollMid` float DEFAULT NULL,
    `MA3` float DEFAULT NULL,
    `MA5` float DEFAULT NULL,
    `MA8` float DEFAULT NULL,
    `MA13` float DEFAULT NULL,
    `MA21` float DEFAULT NULL,
    `MA34` float DEFAULT NULL,
    `MA55` float DEFAULT NULL,
    `MA89` float DEFAULT NULL,
    `Mark` varchar(60) DEFAULT NULL,
    `CurrDelta` float DEFAULT NULL,
    `ExchangeID` varchar(20) DEFAULT NULL,
    `ExchangeInstID` varchar(20) DEFAULT NULL,
    `AskPrice2` float DEFAULT NULL,
    `BidPrice2` float DEFAULT NULL,
    `AskVolume2` int(15) DEFAULT NULL,
    `BidVolume2` int(15) DEFAULT NULL,
    `AskPrice3` float DEFAULT NULL,
    `BidPrice3` float DEFAULT NULL,
    `AskVolume3` int(15) DEFAULT NULL,
    `BidVolume3` int(15) DEFAULT NULL,
    `AskPrice4` float DEFAULT NULL,
    `BidPrice4` float DEFAULT NULL,
    `AskVolume4` int(15) DEFAULT NULL,
    `BidVolume4` int(15) DEFAULT NULL,
    `AskPrice5` float DEFAULT NULL,
    `BidPrice5` float DEFAULT NULL,
    `AskVolume5` int(15) DEFAULT NULL,
    `BidVolume5` int(15) DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `id_UNIQUE` (`id`)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8;
