use AgDB;
CREATE TABLE `ag1412_tick` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT, 
  `InstrumentID` varchar(10) DEFAULT NULL,
  `MySQLTimeStamp` timestamp NULL DEFAULT NULL,
  #`TradingDay` date DEFAULT NULL,
  #`UpdateTime` time DEFAULT NULL,
  `TradingStamp` timestamp NULL DEFAULT NULL,
  `UpdateMillisec` int(11) DEFAULT NULL,
  `LastPrice` float DEFAULT NULL,
  `AskPrice1` float DEFAULT NULL,
  `BidPrice1` float DEFAULT NULL,
  `AskVolume1` int(11) DEFAULT NULL,
  `BidVolume1` int(11) DEFAULT NULL,
  `AveragePrice` float DEFAULT NULL,
  `OpenPrice` float DEFAULT NULL,
  `ClosePrice` float DEFAULT NULL,
  `HighestPrice` float DEFAULT NULL,
  `LowestPrice` float DEFAULT NULL,
  `UpperLimitPrice` float DEFAULT NULL,
  `LowerLimitPrice` float DEFAULT NULL,
  `OpenInterest` int(11) DEFAULT NULL,
  `PreClosePrice` float DEFAULT NULL,
  `PreOpenInterest` int(11) DEFAULT NULL,
  `PreSettlementPrice` float DEFAULT NULL,
  `Volume` int(11) DEFAULT NULL,
  `Mark` varchar(60) DEFAULT NULL,
  `CurrDelta` float DEFAULT NULL,
  `ExchangeID` varchar(45) DEFAULT NULL,
  `ExchangeInstID` varchar(45) DEFAULT NULL,
  `PreDelta` varchar(45) DEFAULT NULL,
  `AskPrice2` float DEFAULT NULL,
  `BidPrice2` float DEFAULT NULL,
  `AskVolume2` int(11) DEFAULT NULL,
  `BidVolume2` int(11) DEFAULT NULL,
  `AskPrice3` float DEFAULT NULL,
  `BidPrice3` float DEFAULT NULL,
  `AskVolume3` int(11) DEFAULT NULL,
  `BidVolume3` int(11) DEFAULT NULL,
  `AskPrice4` float DEFAULT NULL,
  `BidPrice4` float DEFAULT NULL,
  `AskVolume4` int(11) DEFAULT NULL,
  `BidVolume4` int(11) DEFAULT NULL,
  `AskPrice5` float DEFAULT NULL,
  `BidPrice5` float DEFAULT NULL,
  `AskVolume5` int(11) DEFAULT NULL,
  `BidVolume5` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
